prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix vocab: <http://id.nlm.nih.gov/mesh/vocab#>
prefix oio: <http://www.geneontology.org/formats/oboInOwl#>

CONSTRUCT {
  ?x rdfs:label ?y
} WHERE {
  ?x rdfs:label ?y
}
